token:
  secret: "default_very_long_and_secure_jwt_secret_key_here_make_it_at_least_256_bits"
  #  expiration-time: 86400000  # 24 hours in milliseconds
  expiration-time: 24982498 # 24 hours in milliseconds

gateway:
  ip: 127.0.0.1